name: CI tests on dotnet build and test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Restore dependencies
        run: dotnet restore FluentFtpWrapper.csproj
      - name: Build
        run: dotnet build FluentFtpWrapper.csproj --configuration Release --no-restore
      - name: Test
        run: echo "No tests yet" # TODO: Add tests
